config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks, only: [:create, :destroy]
  end

  post '/projects/:project_id/tasks/:id/toggle' => 'tasks#toggle'

  root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  validates :title, presence: {message: "Please input title"},
  length: { minimum: 3, message: "Too short!"}
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates :title, presence: true
  scope :unfinished, -> {where(done: false)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render 'edit'
    end

  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render 'new'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params[:project].permit(:title)
  end

  def set_project
    @project = Project.find(params[:id])
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    redirect_to project_path(@project.id)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to project_path(params[:project_id])
  end

  def toggle
    render nothing: true
    @task = Task.find(params[:id])
    @task.done = !@task.done
    @task.save
  end

  private
  def task_params
    params[:task].permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Taskapp</title>

		<%= csrf_meta_tags %>

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.indigo-pink.min.css">
		<script src="https://storage.googleapis.com/code.getmdl.io/1.0.4/material.min.js"></script>
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

		<%= javascript_include_tag "application" %>

	</head>

	<body>

		<!-- Always shows a header, even in smaller screens. -->
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
			<header class="mdl-layout__header">
				<div class="mdl-layout__header-row">
					<!-- Title -->
					<span class="mdl-layout-title">Task App</span>
					<!-- Add spacer, to align navigation to the right -->
					<div class="mdl-layout-spacer"></div>
					<!--Navigation. We hide it in small screens. -->
					<nav class="mdl-navigation ">
						 <ul>
							<a href="https://twitter.com/masaponto"><i class="fa fa-twitter fa-2x"></i></a>
							<a href="https://github.com/masaponto/task_app"><i class="fa fa-github-square fa-2x"></i></a>
						 </ul>
					</nav>
				</div>
			</header>


			<main class="mdl-layout__content">
				<div class="page-content">

					<%= yield %>

				</div>
			</main>

		</div>

	</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--1-col"></div>

		<form action="#">
			<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label mdl-cell mdl-cell--10-col mdl-cell--4-col-phone mdl-cell--8-col-tablet">
				<%= f.text_field :title, :class => 'mdl-textfield__input' %>
				<%= f.label :title, :class => 'mdl-textfield__label' %>
			</div>

			<% if @project.errors.any? %>
				<%= @project.errors.messages[:title][0] %>
			<% end %>
		</form>

		<div class="mdl-cell mdl-cell--1-col"></div>
	</div>

	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--9-col mdl-cell--2-col-phone mdl-cell--5-col-tablet"></div>

		<div class="mdl-cell mdl-cell--2-col mdl-cell--2-col-phone mdl-cell--2-col-tablet">
			<%= f.submit  :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>

			<%= link_to 'cancel', projects_path,
			:class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect' %>
		</div>

		<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-tablet"></div>
	</div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>

<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--1-col"></div>
	<div class="mdl-cell mdl-cell--10-col">
		<h2>Projects</h2>
	</div>
	<div class="mdl-cell mdl-cell--1-col"></div>
</div>


<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--1-col"></div>

	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp mdl-cell mdl-cell--10-col mdl-cell--4-col-phone mdl-cell--8-col-tablet">

		<tbody>
			<% @projects.each do |project| %>
				<tr>
					<td class="mdl-data-table__cell--non-numeric">
						<span class ="mdl-badge" data-badge = <%= project.tasks.unfinished.count %>>
							<%= link_to project.title, project_path(project.id) %>
						</span>
					</td>

					<td >
						<%= link_to "mode_edit", edit_project_path(project.id) ,
						:class => 'mdl-button mdl-js-button mdl-button--icon material-icons' %>

						<%= link_to "clear", project_path(project.id), method: :delete, data: {confirm: "are you sure?"},
						:class => 'mdl-button mdl-js-button mdl-button--icon material-icons' %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<div class="mdl-cell--3-col-phone mdl-cell--7-col-tablet"> </div>
	<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-phone mdl-cell--1-col-tablet">
		<a href="projects/new">
			<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--2dp" >
				<i class="material-icons">add</i>
			</button>
		</a>
	</div>


</div>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--1-col"></div>
	<div class="mdl-cell mdl-cell--10-col">
		<div class="page-header">
			<h2><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h2>
		</div>
	</div>
	<div class="mdl-cell mdl-cell--1-col"></div>
</div>



<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>

<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--1-col"></div>
	<div class="mdl-cell mdl-cell--10-col">
		<div class="page-header">
			<h2><%= @project.title %></h2>
		</div>
	</div>
	<div class="mdl-cell mdl-cell--1-col"></div>
</div>



<div class="mdl-grid">
    <div class="mdl-cell mdl-cell--1-col"></div>

	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp mdl-cell mdl-cell--10-col">

		<tbody>
			<% @project.tasks.each do |task| %>
				<tr>
					<td class="mdl-data-table__cell--non-numeric">
						<label class="mdl-checkbox mdl-js-checkbox mdl-js-ripple-effect">
							<%= check_box_tag '', '', task.done,
							{'data-id' => task.id, 'data-project_id' => task.project_id, :class => "mdl-checkbox__input" } %>
							<span class ="mdl-checkbox__label">
								<%= label_tag '', task.title %>
							</span>
						</label>
					</td>

					<td>
						<%= link_to "clear", project_task_path(task.project_id, task.id), method: :delete, data: {confirm: "are you sure?"},
						:class => 'mdl-button mdl-js-button mdl-button--icon material-icons' %>
					</td>
				</tr>
			<% end %>

		</tbody>
	</table>

	<div class="mdl-cell mdl-cell--1-col"></div>

</div>


<%= form_for [@project, @project.tasks.build] do |f| %>
	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--1-col"></div>

		<form action="#">

			<div class="mdl-textfield mdl-js-textfield mdl-cell mdl-cell--10-col mdl-cell--4-col-phone mdl-cell--8-col-tablet">
				<%= f.text_field :title, :class => 'mdl-textfield__input' %>
				<%= f.label :title, :class => 'mdl-textfield__label' %>
			</div>
		</form>

		<div class="mdl-cell mdl-cell--1-col"></div>
	</div>


	<div class="mdl-grid">
		<div class="mdl-cell mdl-cell--9-col mdl-cell--2-col-phone mdl-cell--5-col-tablet"></div>
		<div class="mdl-cell mdl-cell--2-col mdl-cell--2-col-phone mdl-cell--2-col-tablet">

			<%= f.submit :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>

			<%= link_to t('.back', :default => t("helpers.links.back")),
				projects_path, :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect'  %>

		</div>

		<div class="mdl-cell mdl-cell--1-col mdl-cell--1-col-tablet"></div>
	</div>

<% end %>

<script>
 $(function() {
	 $("input[type=checkbox]").click(function() {
		 $.post('/projects/' + $(this).data('project_id') + '/tasks/' + $(this).data('id') + '/toggle')
	 });
 });
</script>